# coding: utf-8

# flake8: noqa
"""
    Locationforecast

    Weather forecast for a specified place

    The version of the OpenAPI document: 2.0
    Contact: weatherapi-adm@met.no
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.forecast import Forecast
from openapi_client.models.forecast_meta import ForecastMeta
from openapi_client.models.forecast_summary import ForecastSummary
from openapi_client.models.forecast_time_instant import ForecastTimeInstant
from openapi_client.models.forecast_time_period import ForecastTimePeriod
from openapi_client.models.forecast_time_step import ForecastTimeStep
from openapi_client.models.forecast_time_step_data import ForecastTimeStepData
from openapi_client.models.forecast_time_step_data_instant import ForecastTimeStepDataInstant
from openapi_client.models.forecast_time_step_data_next12_hours import ForecastTimeStepDataNext12Hours
from openapi_client.models.forecast_time_step_data_next1_hours import ForecastTimeStepDataNext1Hours
from openapi_client.models.forecast_time_step_data_next6_hours import ForecastTimeStepDataNext6Hours
from openapi_client.models.forecast_units import ForecastUnits
from openapi_client.models.metjson_forecast import METJSONForecast
from openapi_client.models.point_geometry import PointGeometry
from openapi_client.models.weather_symbol import WeatherSymbol
