# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place

    The version of the OpenAPI document: 2.0
    Contact: weatherapi-adm@met.no
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.point_geometry import PointGeometry

class TestPointGeometry(unittest.TestCase):
    """PointGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PointGeometry:
        """Test PointGeometry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PointGeometry`
        """
        model = PointGeometry()
        if include_optional:
            return PointGeometry(
                coordinates = [60.5, 11.59, 1001],
                type = 'Point'
            )
        else:
            return PointGeometry(
                coordinates = [60.5, 11.59, 1001],
                type = 'Point',
        )
        """

    def testPointGeometry(self):
        """Test PointGeometry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
