# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place

    The version of the OpenAPI document: 2.0
    Contact: weatherapi-adm@met.no
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.data_api import DataApi


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataApi()

    def tearDown(self) -> None:
        pass

    def test_classic_format_get(self) -> None:
        """Test case for classic_format_get

        """
        pass

    def test_classic_get(self) -> None:
        """Test case for classic_get

        """
        pass

    def test_compact_format_get(self) -> None:
        """Test case for compact_format_get

        """
        pass

    def test_compact_get(self) -> None:
        """Test case for compact_get

        """
        pass

    def test_complete_format_get(self) -> None:
        """Test case for complete_format_get

        """
        pass

    def test_complete_get(self) -> None:
        """Test case for complete_get

        """
        pass

    def test_status_format_get(self) -> None:
        """Test case for status_format_get

        """
        pass

    def test_status_get(self) -> None:
        """Test case for status_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
