# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place

    The version of the OpenAPI document: 2.0
    Contact: weatherapi-adm@met.no
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.metadata_api import MetadataApi


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetadataApi()

    def tearDown(self) -> None:
        pass

    def test_changelog_get(self) -> None:
        """Test case for changelog_get

        """
        pass

    def test_healthz_get(self) -> None:
        """Test case for healthz_get

        """
        pass

    def test_schema_get(self) -> None:
        """Test case for schema_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
