# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place

    The version of the OpenAPI document: 2.0
    Contact: weatherapi-adm@met.no
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.forecast_time_step_data_instant import ForecastTimeStepDataInstant

class TestForecastTimeStepDataInstant(unittest.TestCase):
    """ForecastTimeStepDataInstant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastTimeStepDataInstant:
        """Test ForecastTimeStepDataInstant
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastTimeStepDataInstant`
        """
        model = ForecastTimeStepDataInstant()
        if include_optional:
            return ForecastTimeStepDataInstant(
                details = openapi_client.models.forecast_time_instant.ForecastTimeInstant(
                    air_pressure_at_sea_level = 1017.23, 
                    air_temperature = 17.1, 
                    cloud_area_fraction = 95.2, 
                    cloud_area_fraction_high = 95.2, 
                    cloud_area_fraction_low = 95.2, 
                    cloud_area_fraction_medium = 95.2, 
                    dew_point_temperature = 8.1, 
                    fog_area_fraction = 95.2, 
                    relative_humidity = 81.1, 
                    wind_from_direction = 121.3, 
                    wind_speed = 5.9, 
                    wind_speed_of_gust = 15.9, )
            )
        else:
            return ForecastTimeStepDataInstant(
        )
        """

    def testForecastTimeStepDataInstant(self):
        """Test ForecastTimeStepDataInstant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
