# coding: utf-8

"""
    Locationforecast

    Weather forecast for a specified place

    The version of the OpenAPI document: 2.0
    Contact: weatherapi-adm@met.no
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.forecast_summary import ForecastSummary

class TestForecastSummary(unittest.TestCase):
    """ForecastSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForecastSummary:
        """Test ForecastSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForecastSummary`
        """
        model = ForecastSummary()
        if include_optional:
            return ForecastSummary(
                symbol_code = clearsky_day
            )
        else:
            return ForecastSummary(
                symbol_code = clearsky_day,
        )
        """

    def testForecastSummary(self):
        """Test ForecastSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
